[tool.poetry]
name = "rpa-qt"
version = "0.1.0"
description = ""
authors = ["Nick Kao <kaonick@gmail.com>"]
readme = "README.md"
packages = [{include = "rpa_qt"}]

[tool.poetry.dependencies]
python = "^3.9"
# os
psutil = "^6.1.0" # pid
tqdm = "^4.67.1" # progress bar
schedule = "^1.2.2" # schedule

# crawler_libs
webdriver-manager = "^4.0.2"
chromedriver-autoinstaller = "^0.6.4"
selenium = "^4.27.1"
seleniumbase = "^4.33.11"
undetected-chromedriver = "^3.5.5"
selenium-stealth ="^1.0.6"
# data
#pandas = "^2.1.4"
pandas = "^2.2.3"
pydantic = "^2.10.3"
tabulate = "^0.9.0"
scikit-learn = "^1.4.0"

# db
sqlmodel = "^0.0.22" #"^0.0.16"
mysql-connector-python = "^8.3.0"
cx-oracle = "^8.3.0"
pymssql = "^2.2.11"
elasticsearch = "^8.17.0"

# document
lxml = "^5.3.0"
openpyxl = "^3.1.5"  # read excel need
html5lib = "^1.1" # html parser

# web
fastapi = "^0.115.0"
uvicorn = "^0.31.0"
python-logging-loki = "^0.3.1"
websockify = "^0.12.0"
#python-telegram-bot = "^21.10"
python-telegram= "^0.19.0"
# heavy task
celery = "^5.4.0"
gevent = "^24.11.1"
redis = "^5.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
